config/routes.rb
TwitterExample::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get "twittertweets/search"
    end
  end
    mount CookieAlert::Engine => "/cookie-alert"
  #get "twittertweets/search"
  post "twittertweets/search"
  get "twittertweets/getSources"
  get "home/contact_us"
   get "home/about_us"
   get "home/plans"
   get "home/help"
   get "home/contactthank"
   get "home/subscribe"
  post "twittertweets/search"
  get "twittertweets/index"
  get "userfeed/create"
  post "tweets/search"
  get "tweets/search"
  post "tweets/searh"
  get "tweets/searh"
   get "tweets/index"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 
  resources :tweets, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show, :index]
 
  root to: "home#index"
end

app/views/cookie_alert/cookies/_primary_alert.html.erb
  <div id='cookie_alert' >
    <div id='cookie_alert_message'>
    <div class="alert alert-info">
        <div id='cookie_alert_title'>
        <b>Cookies:</b>
      </div>
      <div id='cookie_alert_text'>
        
        We use cookies to help personalise and improve your web experience. 
        By using our website you consent to our use of cookies, some of which may have already been set on your device. 
        View our <a href="cookie_policy">Cookie Policy</a> to learn more. 
        <%= link_to "X", cookie_alert_path, id: 'cookie_alert_close', remote: true %>
      </div>
    </div>
  </div>
        </div>

app/views/cookie_alert/cookies/_secondary_alert.html.erb
  <div id='cookie_alert' class='secondary-alert' >
    <div id='cookie_alert_message'>
    <div class="alert alert-info">
        <div id='cookie_alert_title'>
        <b>Cookies:</b>
      </div>
      <div id='cookie_alert_text' style='display:none;'>
        
        We use cookies to help personalise and improve your web experience. 
        By using our website you consent to our use of cookies, some of which may have already been set on your device. 
        View our <a href="cookie_policy">Cookie Policy</a> to learn more. 
        <%= link_to "X", cookie_alert_path, id: 'cookie_alert_close', remote: true %>
      </div>
    </div>
  </div>
  </div>
        

app/views/cookie_alert/cookies/cookie_accepted.js.erb
$('#cookie_alert').remove();