config/routes.rb
TwitterExample::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get "twittertweets/search"
    end
  end
    mount CookieAlert::Engine => "/cookie-alert"
  #get "twittertweets/search"
  post "twittertweets/search"
  get "twittertweets/getSources"
  get "home/contact_us"
   get "home/about_us"
   get "home/plans"
   get "home/help"
   get "home/contactthank"
   get "home/subscribe"
  post "twittertweets/search"
  get "twittertweets/index"
  get "userfeed/create"
  post "tweets/search"
  get "tweets/search"
  post "tweets/searh"
  get "tweets/searh"
   get "tweets/index"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 
  resources :tweets, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show, :index]
 
  root to: "home#index"
end

app/views/shared/_analyze_sources.html.erb
<table class="table table-striped" id="datatable" style='width: 90%; display:none;'>
<tr>
<th>Sources</th>
     <th>Count</th>
<% for tweet in @ThisHashSource %>
<tr>
<td class="text-primary" class="bg-primary">    <%=tweet[0]%></td>
<td> <%=tweet[1]%> </td>
     <% end %>
</table>

app/views/shared/_tweetfromdb.html.erb
<div class="container" ><table class="table table-striped" style='width: 100%;' summary="This table displays the tweets in a tabular fashion. In sequence they are as follows Location,Profile Image,Number of Followers,Num of Status, Tweet Text, Lattitude, Longitude, Source and Retweet_count">
<CAPTION>Tweet details of evert tweet</CAPTION>
<tr>
<th id="header1">Location</th>
     <th id="header2">Profile Image</th>
    <th id="header3">Number of Followers</th>
    <th id="header4">Num of Status </th>
    <th id="header5"> Tweet Text</th>
     <th id="header6">Lattitude</th>
    <th id="header7"> Longitude</th>
     <th id="header8"> Source</th>
     <th id="header9"> Retweet_count</th></tr>
<% for tweet in @tweets %>
<tr>
<td class="text-primary" headers="header1">    <%=tweet.location%></td>
<td headers="header2"> <img   class="img-circle"src=<%=tweet.profile_pic%>/> </td>
  <td headers="header3"> <%=tweet.friends_count%></td>
  <td headers="header4">  <%=tweet.status_count%></td>
  <td headers="header5">    <%=tweet.tweet_text%></td>
  <td headers="header6">  <%=tweet.lattitude%></td>
    <td headers="header7">  <%=tweet.longitude%></td>
     <td headers="header8">  <%=tweet.source%></td>
     <td headers="header9">  <%=tweet.retweet_count%></td></tr>
     <% end %>
</table>


<table class="table table-striped" style='width: 100%; display:none;' id="tweetstable" >
<tr><th>Picture</th>
    <th>infowindow</th>
     <th>lat</th>
    <th>lng</th></tr>
<% for tweet in @tweets %>
<tr>
<td> <%=tweet.profile_pic%> </td>
  <td> <img src="<%=tweet.profile_pic%>" class="img-circle"/><%=tweet.tweet_text%></b> <i>Location : <%=tweet.location%></i></td>
  <td>  <%=tweet.lattitude%></td>
    <td>  <%=tweet.longitude%></td>
     <% end %>
</table>
</div>


  

app/views/shared/_tweetsearch.html.erb
<div class="container">
            <% if current_user %>
      <%= form_for @twittertweets url: twittertweets_search_path , method: :post do |t| %>
  <h2 style="font-weight:bold;font-size:24px;" ><%= t.text_field :hashtag , :size => 80%>
  <button type="#{<% t.submit %>}" class="btn btn-primary" >Search</button> </h2>
  <% end %><%end%><hr/>
</div>