config/routes.rb
TwitterExample::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get "twittertweets/search"
    end
  end
    mount CookieAlert::Engine => "/cookie-alert"
  #get "twittertweets/search"
  post "twittertweets/search"
  get "twittertweets/getSources"
  get "home/contact_us"
   get "home/about_us"
   get "home/plans"
   get "home/help"
   get "home/contactthank"
   get "home/subscribe"
  post "twittertweets/search"
  get "twittertweets/index"
  get "userfeed/create"
  post "tweets/search"
  get "tweets/search"
  post "tweets/searh"
  get "tweets/searh"
   get "tweets/index"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 
  resources :tweets, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show, :index]
 
  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
  end
  def show
  	@user_timeline=current_user.get_timeline()
  	#@tweets=current_user.search()
  	#@user_followers=current_user.get_followers()
  end
def contact_us
end
def about_us
end

def plans
end

def subscribe
	flash[:notice] = "You have successfully subscribed to this plan."
	redirect_to root_url
end

def contactthank
	flash[:notice] = "Thanks for Contacting! We will contact you within 24 hours."
	redirect_to root_url
end

def help
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about_us.html.erb
<div class="container">
    <div class="span3 well" style="margin-Top:3%;">
        <center>
        <h1>About the developer</h1>
        <a href="#aboutModal" data-toggle="modal" data-target="#myModal"><img src="/images/khushal.jpg" name="aboutme" width="140" height="140" class="img-circle"></a>
        <h3>Khushal Dave</h3>
        <h4>MSc (Cloud Computing)</h4>
        <h5>National College of Ireland</h5>
        <h5>Dublin-1 Ireland</h5>
        <em>Click face for more</em>
		</center>
     </div>
     <div class="jumbotron">
<blockquote>
  <h3>We make your <span class="label label-warning">Marketing</span> more effective and precise. Just give it a try!</h3>
  <h4>We believe in customers<cite title="Source Title"> Just like you do.</cite></h4>
</blockquote >
</div>
<div class="jumbotron">
<blockquote>
 <h3><span class="label label-warning">NCIRL Says</span></h3>
  <h4>The Focus on the target market wouldn't be that easy without Tweetsgeek.
    Thanks a million !</h4>
</blockquote>
   
   
    </div>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <h4 class="modal-title" id="myModalLabel">More About Khushal Dave</h4>
                    </div>
                <div class="modal-body">
                    <center>
                    <img src="/images/khushal.jpg" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
                    <h3 class="media-heading">Khushal Dave <small>Ireland/India</small></h3>
                    <span><strong>Skills: </strong></span>
                        <span class="label label-warning">HTML5/CSS</span>
                        <span class="label label-info">Rails</span>
                        <span class="label label-info">J2EE</span>
                        <span class="label label-success">Cloud Computing</span>
                        <span class="label label-info">UX</span>
                        <span class="label label-warning">BootStrap</span>
                    </center>
                    <hr>
                    <center>
                    <p class="text-left"><strong>How we help </strong><br>
                       I have designed this application for Advanced Client Side Scripting Project.
                       This application helps the marketting team of any company to track their hashtags and act accordingly.</p>
                       <p class="text-left">We can help you to efffectively target your markets and track your competitiors!</p>
                       <p class="text-left"> We present information into an effective visual medium which is easy to interpret and thus create effective communication channel between you and the strategy team.</p>
                    <br>
                    </center>
                </div>
                <div class="modal-footer">
                    <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Looks Great !</button>
                    </center>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/contact_us.html.erb
<div class="jumbotron jumbotron-sm">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                <h1 class="h1">
                    Contact us <small>Feel free to contact us</small></h1>
            </div>
        </div>
    </div>

    <div id="ThanksMsg" style="width:80px;height:80px;display:none;"><p>We will contact you soon!<p></div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="well well-sm">
                <form action="contactthank" method="get">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Name</label>
                            <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                        </div>
                        <div class="form-group">
                            <label for="email">
                                Email Address</label>
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" /></div>
                        </div>
                        <div class="form-group">
                            <label for="subject">
                                Subject</label>
                            <select id="subject" name="subject" class="form-control" required="required">
                                <option value="na" selected="">Choose One:</option>
                                <option value="service">General Customer Service</option>
                                <option value="suggestions">Suggestions</option>
                                <option value="product">Product Support</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="name">
                                Message</label>
                            <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                                placeholder="Message"></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-primary pull-right" id="btnContactUs">
                            Send Message</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d152521.48963088408!2d-6.258091800000001!3d53.32269839999999!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48670ea895414de5%3A0x23250627154a393!2s25+Charleston+Ave!5e0!3m2!1sen!2s!4v1398714980581" width="400" height="200" frameborder="0" style="border:0"></iframe>
            <form>
            <legend></span> Our office</legend>
            <address>
                <strong>TweetsGeek Inc.</strong><br>
                25, Charlston Avenue<br>
                Ranelagh,Dublin-6<br>
                <abbr title="Phone">
                    P:</abbr>
                (1)43737945
            </address>
            <address>
                <strong>Khushal Dave</strong><br>
                <a href="mailto:#">khushal@Tweetsgeek.com</a>
            </address>
            </form>

        </div>
    </div>
</div>


app/views/home/help.html.erb

<div class="container"  style="margin-top: 5%;">

<h1>Please watch this video to learn</h1><h3>to use this application.</h3>
<iframe width="768" height="600" src="//www.youtube.com/embed/m46DMCkr6OQ?rel=0" frameborder="0" allowfullscreen></iframe></div>

app/views/home/index.html.erb
<%= javascript_include_tag "killercarousel.js", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag    "killercarousel.css", media: "all", "data-turbolinks-track" => true%>

<style type="text/css">

            body {
                font-family: arial, sans-serif;
                color: #444;
                font-size: 16px;
                padding:0px;
                margin:0px;
            }

            p {
                line-height: 20px;
            }

            code {
                font-weight: bold;
                color: #f44;;
            }
            a {
                color:#3d8dde;
            }

            #wrapper {
                padding:10px;
            }
        </style>

        <!-- Styles for the Carousel -->
        <style type = "text/css">

            /* CSS for images inside item wrapper */
            .kc-item img {
                position:absolute;
                pointer-events: none;   /* Make images non-selectable. */
                width:100%;             /* Make images expand to wrapper size (used in 2d modes). */
            }

        </style>

        <script type = "text/javascript">
            // Create the carousel.
            $(function() {
                $('.kc-wrap').KillerCarousel({
                    // Default natural width of carousel.
                    width: 800,
                    // Item spacing in 3d (has CSS3 3d) mode.
                    spacing3d: 120,
                    // Item spacing in 2d (no CSS3 3d) mode. 
                    spacing2d: 120,
                    showShadow: true,
                    showReflection: true,
                    // Looping mode.
                    infiniteLoop: true,
                    // Scale at 75% of parent element.
                    autoScale: 100
                });
            });
        </script>
  <div class="container" style="Margin-Top: 5%;">
  <img src="images/welcome.png" height="50">


<div class="col-md-9">
  
<div class = "kc-wrap">
                <!-- Carousel items follow -->
                
                <div class="kc-item">
                    <img src="images/7.png" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/8.png" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/9.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/10.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/11.jpg" alt = " "  height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/1.png" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/2.png" alt = " " height="250" width="200">
                </div> 
                <div class="kc-item">
                    <img src="images/3.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/4.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/5.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/6.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/12.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/13.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/14.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/15.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/16.jpg" alt = " " height="250" width="200">
                </div>
                 
                <div class="kc-item">
                    <img src="images/18.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/19.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/20.jpg" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/21.png" alt = " " height="250" width="200">
                </div>
                <div class="kc-item">
                    <img src="images/22.jpg" alt = " " height="250" width="200">
                </div>
            </div>
</div>
<div class="col-md-3">
<a class="twitter-timeline" data-dnt="true" href="https://twitter.com/TweetsGeeks" data-widget-id="460500503604895745">Tweets by @TweetsGeeks</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>
</div>

app/views/home/plans.html.erb
<div class="container" >
<div style="margin-Top:5%;">
<h1>Subscribe Plans</h1>
    <div class="row">
        <div class="col-xs-12 col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Bronze</h3>
                </div>
                <div class="panel-body">
                    <div class="the-price">
                        <h1>
                          €20<span class="subscript">/mo</span></h1>
                        <small>1 month FREE trial</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                1 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                1 Hashtag
                            </td>
                        </tr>
                        <tr>
                            <td>
                                100K API Request
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                No Instant Updates
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Monthly Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <a href="http://localhost:3000/home/subscribe" class="btn btn-success" role="button">Subscribe</a>
                    1 month FREE trial</div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="panel panel-success">
                <div class="cnrflash">
                    <div class="cnrflash-inner">
                        <span class="cnrflash-label">MOST
                            <br>
                            POPULR</span>
                    </div>
                </div>
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Silver</h3>
                </div>
                <div class="panel-body">
                    <div class="the-price">
                        <h1>
                            €40<span class="subscript">/mo</span></h1>
                        <small>1 month FREE trial</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                1 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                5 Hashtags
                            </td>
                        </tr>
                        <tr>
                            <td>
                                100K API Access
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Daily Updates
                            </td>
                        </tr>
                         
                        <tr  >
                            <td>
                                Weekly Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <a href="http://localhost:3000/home/subscribe" class="btn btn-success" role="button">Subscribe</a>
                    1 month FREE trial</div>
            </div>
        </div>
        <div class="col-xs-12 col-md-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        Gold</h3>
                </div>
                <div class="panel-body">
                    <div class="the-price">
                        <h1>
                            €55<span class="subscript">/mo</span></h1>
                        <small>1 month FREE trial</small>
                    </div>
                    <table class="table">
                        <tr>
                            <td>
                                1 Account
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                10 Hashtags
                            </td>
                        </tr>
                        <tr>
                            <td>
                                200K API Access
                            </td>
                        </tr>
                        <tr class="active">
                            <td>
                                Instant Updates
                            </td>
                        </tr>
                         
                        <tr  >
                            <td>
                                Daily Reports
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="panel-footer">
                    <a href="http://localhost:3000/home/subscribe" class="btn btn-success" role="button">Subscribe</a> 1 month FREE trial</div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/home/show.html.erb
<% if !current_user.nil? %>
    <p>Click The link below to send a tweet.</p>
    <%= link_to "Send a Tweet", new_tweet_path %>
    <table>
  <tr>
    <th>Tweet</th>
    <th> Hashtags</th>
    <th>Source</th>
  </tr>
 
    <% @user_timeline.each do |tweet| %>
  <tr><td>    <%=tweet.user["location"]%></td>
  <td>    <%=tweet.hashtags["text"]%></td>
  <td>    <%=tweet.text%></td></tr>
<%end%>

 


<% else %>
    <p>You must log in to send a tweet.</p>
<% end %>


 