config/routes.rb
TwitterExample::Application.routes.draw do

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get "twittertweets/search"
    end
  end
    mount CookieAlert::Engine => "/cookie-alert"
  #get "twittertweets/search"
  post "twittertweets/search"
  get "twittertweets/getSources"
  get "home/contact_us"
   get "home/about_us"
   get "home/plans"
   get "home/help"
   get "home/contactthank"
   get "home/subscribe"
  post "twittertweets/search"
  get "twittertweets/index"
  get "userfeed/create"
  post "tweets/search"
  get "tweets/search"
  post "tweets/searh"
  get "tweets/searh"
   get "tweets/index"
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
 
  resources :tweets, only: [:index, :create]
  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show, :index]
 
  root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetGeek</title>
     <!-- Bootstrap -->
    <%= javascript_include_tag "jquery-1.11.0.min.js", "data-turbolinks-track" => true %>
    <%= stylesheet_link_tag    "bootstrap.min.css", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "bootstrap.min.js", "data-turbolinks-track" => true %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
     <%= javascript_include_tag "application" %>
    <%= yield :scripts%>
    <%= csrf_meta_tags %>
  </head>
  <body>
  
  
  <a href="#maincontent" class="sr-only" title="You can directly skip to the main content">Skip to main content</a>
   <div class="container">
  <div class="navbar navbar-default navbar-fixed-top"  role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="http://localhost:3000">TweetGeek </a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "Search Live", tweets_index_path, data: { keybinding: 'l' }%></li>
    <li><%= link_to "Want more !", twittertweets_index_path, data: { keybinding: 'd' }%></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Help<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="/home/help">How to do!</a></li>
        </ul>
      </li>
    </ul>
    
     
    <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
        <li>Signed in as <span class="label label-success"><%= current_user.name %></span></li>
        <li>
        <a href="/signout">Sign Out</a></li>
      <% else %>
       
       <a href="/auth/twitter"> <%= image_tag "sign-in-with-twitter.png" %></a>
      <% end %>
         <li><a href="#shortcut" class="dropdown-toggle" data-toggle="modal">Accessiblity</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
        <ul class="dropdown-menu">
<li><a href="/home/about_us">About Us!</a></li>
<li><a href="/home/contact_us">Contact Us!</a></li>
          <li class="divider"></li>

          <li class="dropdown-header">Plan</li>
          <li><a href="/home/plans">Subscribe</a></li>
        </ul>
      </li>
    </ul>
  </div>
</div>
  </div>
    
<% if flash[:notice] %>
 <div class="container" style="margin-top: 5%;">
<div class="container">
    <div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">X</button>
  <%= flash[:notice]%>
</div> </div>
  <%end%></div>


  <div id="maincontent">
    <%= yield %>
</div>


    <div class="footer">
</div> 
<div class="navbar-fixed-bottom" style='background-color: #f5f5f5;'><%= display_cookie_alert %>
     <div class="row">
      <div class="col-md-1"></div>
  <div class="col-md-4"><p>Thanks for using!</p><p>&copy; 2014 <span class="label label-primary">TweetsGeek Inc.</span>
 All rights reserved</p></div>
  <div class="col-md-5"><p></p> <span class="label label-primary">Marketing</span>
<span class="label label-success">Strategy</span>
<span class="label label-info">Prediction</span>
<span class="label label-warning">Risk Analysis</span>
<span class="label label-danger">Feedbacks</span></div>


  <div class="col-md-2"><a href="#"><p></p> <p class="label label-primary text-right">@khushaldave</p></a></div>
</div>
        
      </div>

<div class="modal fade" id="shortcut" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">ShortCut Keys</h4>
      </div>
      <div class="modal-body">
       <p>Keyboard ShortCuts have been added for accessiblity.</p>
       <table class="table table-hover">
       <tr>
       <th>Sr. No</th><th>Navigation</th><th>Shortcut Key</th>
       </tr>
       <tr><td>1.</td><td>Search Live Data</td><td>l</td></tr>
       <tr><td>2.</td><td>Search DataBase</td><td>d</td></tr>
       </table> 

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
  </body>
</html>